# Generated by Django 6.0.7 on 2026-07-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('plate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=10)),
                ('driver_licensenumber', models.CharField(max_length=10)),
                ('assigned_truck_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver_id', to='core.truck')),
            ],
        ),
    ]
