# Generated by Django 6.0.7 on 2026-07-30 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_location',
            field=models.CharField(choices=[('IT', 'In Transit'), ('AT', 'At Depot'), ('AD', 'Arrived Destination'), ('OR', 'On Route')], default='AT', max_length=3),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(choices=[('IS', 'In Service'), ('AV', 'Available'), ('UNAV', 'Unavailable'), ('OOS', 'Out of Service')], default='IS', max_length=5),
        ),
        migrations.AlterField(
            model_name='truck',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
