# Generated by Django 6.0.7 on 2026-08-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_driver_assigned_truck_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='assigned_truck_id',
            new_name='truck',
        ),
    ]
