# Generated by Django 6.0.7 on 2026-08-10 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_assigned_truck_id_driver_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('planned_miles', models.FloatField(default=0)),
                ('actual_miles', models.FloatField(default=0)),
                ('loaded_miles', models.FloatField(default=0)),
                ('empty_miles', models.FloatField(default=0)),
                ('cpm', models.FloatField(default=0)),
                ('pay', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('act', 'active'), ('com', 'completed'), ('can', 'canceled'), ('inc', 'incomplete')], default='act', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.driver')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.truck')),
            ],
        ),
    ]
