# Generated by Django 6.0.7 on 2026-08-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='truck',
        ),
    ]
