# Generated by Django 6.0.7 on 2026-08-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_trip_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_licensenumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='core.truck'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('inpro', 'inprogress'), ('plan', 'planned'), ('com', 'completed'), ('can', 'canceled'), ('inc', 'incomplete')], default='plan', max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(choices=[('IR', 'In Repair'), ('AV', 'Available'), ('UNAV', 'Unavailable'), ('OOS', 'Out of Service')], default='IR', max_length=5),
        ),
    ]
