# Generated by Django 6.0.7 on 2026-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_driver_driver_licensenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(choices=[('IR', 'In Repair'), ('AV', 'Available'), ('UNAV', 'Unavailable'), ('OOS', 'Out of Service')], default='AV', max_length=5),
        ),
    ]
