# Generated by Django 6.0.7 on 2026-08-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_truck_truck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('av', 'AVAILABLE'), ('ua', 'UNAVAILABLE')], default='av', max_length=25),
        ),
    ]
