# Generated by Django 6.0.7 on 2026-08-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_driver_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.truck'),
        ),
    ]
